import { initializeApp, getApps } from "firebase/app";
import {
  getFirestore,
  collection,
  addDoc,
  setDoc,
  deleteDoc,
  getDocs,
  doc,
  onSnapshot,
  serverTimestamp,
  updateDoc,
  query,
  limit,
  orderBy,
  getDoc,
  where,
} from "firebase/firestore";
import {
  // getAuth,
  onAuthStateChanged,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  updateProfile,
  updatePassword,
  reauthenticateWithCredential,
  sendEmailVerification,
  EmailAuthProvider,
  deleteUser,
  signOut,
  initializeAuth,
} from "firebase/auth";
import { getStorage, ref, uploadBytes, getDownloadURL } from "firebase/storage";
const firebaseConfig = {
  apiKey: "AIzaSyD2c5D7MtdLHYcTQpm2GJsDb2PY36lGmss",
  authDomain: "sniiz-sendr.firebaseapp.com",
  databaseURL: "https://sniiz-sendr-default-rtdb.firebaseio.com",
  projectId: "sniiz-sendr",
  storageBucket: "sniiz-sendr.appspot.com",
  messagingSenderId: "762806681066",
  appId: "1:762806681066:web:90d314bbed15da56cb8693",
};
if (!getApps().length) initializeApp(firebaseConfig);
const auth = initializeAuth(app, {
  persistence: [
    indexedDBLocalPersistence,
    browserLocalPersistence,
    browserSessionPersistence,
  ],
});
export {
  // getAuth,
  onAuthStateChanged,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  reauthenticateWithCredential,
  updateProfile,
  updatePassword,
  signOut,
  sendEmailVerification,
  collection,
  addDoc,
  getFirestore,
  onSnapshot,
  serverTimestamp,
  query,
  EmailAuthProvider,
  orderBy,
  setDoc,
  doc,
  deleteUser,
  deleteDoc,
  where,
  getDocs,
  updateDoc,
  getDoc,
  getStorage,
  ref,
  uploadBytes,
  getDownloadURL,
  limit,
  auth,
};
